### ISSUE TITLE
NoClassDefFoundError on Android 4.3

### ISSUE THREAD

**Issue by cyfer** [KoMinkyu/teaspoon#7]
Hi,
App startup fails on a Samsung phone running Android 4.3 (Model GT-I9300), with a NoClassDefFoundError on Teaspoon.initialise(). I'm using Teaspoon 0.3.4

05-27 14:32:52.284 5867-5867/uk.co.cyferapps.restaurants E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           java.lang.NoClassDefFoundError: teaspoon.ExecuteEngineFactory
                                                                               at teaspoon.TeaSpoon.initialize(TeaSpoon.java:36)
                                                                               at uk.co.cyferapps.restaurants.application.NearMeApplication.onCreate(NearMeApplication.java:15)
                                                                               at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4684)
                                                                               at android.app.ActivityThread.access$1400(ActivityThread.java:159)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                               at android.os.Looper.loop(Looper.java:176)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5419)
                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:525)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
                                                                               at dalvik.system.NativeStart.main(Native Method)

Any idea how to work around this?

**Comment by KoMinkyu** [comment]
Thank you for your specific report.
I will give you feedback asap.

**Comment by KoMinkyu** [comment]
Is multidex enabled?

**Comment by KoMinkyu** [comment]
I tested in same device and same version of android, but I can't reproduce that issue.
Can I request more detail information about your work environment?

**Comment by cyfer** [comment]
Hi,

Thanks for the reply. Just for the record, I can reproduce the issue both on a physical device AND on a Genymotion emulator of a Samsung Galaxy S3, API 18 (Android 4.3).

My work environment:
Macbook Pro (two of them actually)
Android Studio 2.1.1, for OSX.
JRE: 1.6.0_65-b14-468-11M4833 x86_64 ... I have installed Java 8 on my second machine but don't have the JRE for it at hand right now. Same crash was observed on both machines.

multidex is enabled.

Any other info you would like? I can provide you the build.gradle files if you think they will help. 

Thanks for your time and effort!

**Comment by cyfer** [comment]
One more update: The crash is reproducible on every 4.x Android version I have tried on different device emulators on Genymotion.

Versions 5.x and above work fine.

**Comment by KoMinkyu** [comment]
I think I have to test with Genymotion.
I will give you additional feedback soon. thanks!

**Comment by KoMinkyu** [comment]
I think this issue occur when multidex is not working properly.

Can you check your multidex settings using these [methods](http://stackoverflow.com/a/27709640).

**Comment by cyfer** [comment]
That was it! I was missing the "extends MultiDexApplication" bit in the Application file. Added it and it worked on 4.1.1 straight away!

Now that we figured this out, maybe add this information to the wiki of the project so that others don't encounter the same issue.

Thanks so much for the solution!

**Comment by KoMinkyu** [comment]
Great to here that!
I will remove bug label about this issue.
